apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: sockshop
spec:
  replicas: 1
  selector:
     matchLabels:
       app: orders-db
  template:
    metadata:
      labels:
       app: orders-db
    spec:
      containers:
      - name: orders-db
        image: mongo:latest
        ports:
        - containerPort: 27017