apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-sql
  namespace: sockshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-sql
  template:
    metadata:
      labels:
        app: payment-sql
    spec:
      containers:
        - name: payment-sql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpass
            - name: MYSQL_DATABASE
              value: payment
            - name: MYSQL_USER
              value: paymentuser
            - name: MYSQL_PASSWORD
              value: paymentpass
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 500m
              memory: 800Mi
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}